// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace TrialPE.Models;

public partial class LionProfile
{
    public int LionProfileId { get; set; }

    [Required(ErrorMessage = "Lion Type is required.")]
    [Display(Name = "Lion Type")]
    public int LionTypeId { get; set; }

    [Required(ErrorMessage = "Lion Name is required.")]
    [StringLength(100, MinimumLength = 4, ErrorMessage = "Lion Name must be at least 4 characters long.")]

    [RegularExpression(@"^(?!.*[#@&()])[A-Z][a-z]*( [A-Z][a-z]*)*$", ErrorMessage = "Each word must start with a capital letter and no special characters (#, @, &, (, )).")]
    [Display(Name = "Lion Name")]
    public string LionName { get; set; }

    [Required(ErrorMessage = "Weight is required.")]
    [Range(30.01, double.MaxValue, ErrorMessage = "Weight must be greater than 30.")]
    public double Weight { get; set; }

    [Required(ErrorMessage = "Characteristics are required.")]
    public string Characteristics { get; set; }

    [Required(ErrorMessage = "Warning is required.")]
    public string Warning { get; set; }

    public DateTime ModifiedDate { get; set; }

    public virtual LionType LionType { get; set; }
}