// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EVCMS.Repositories.DucPV.Models;

public partial class ChargingStation
{
    public int StationId { get; set; }

    public string StationName { get; set; }

    public int? NumberOfPoints { get; set; }

    public string Address { get; set; }

    public decimal? PricePerKwh { get; set; }

    public int? OperatedByStaffId { get; set; }

    public int? AssignedByAdminId { get; set; }

    public TimeOnly? OpeningHours { get; set; }

    public TimeOnly? ClosingHours { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public bool? Status { get; set; }

    public virtual Admin AssignedByAdmin { get; set; }

    public virtual ICollection<ChargingPoint> ChargingPoints { get; set; } = new List<ChargingPoint>();

    public virtual Staff OperatedByStaff { get; set; }
}