// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EVCMS.Repositories.DucPV.Models;

public partial class IssueReport
{
    public int ReportId { get; set; }

    public int? PointId { get; set; }

    public int? ReportedByStaffId { get; set; }

    public string Description { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? ResolvedAt { get; set; }

    public bool? Status { get; set; }

    public virtual ChargingPoint Point { get; set; }

    public virtual Staff ReportedByStaff { get; set; }
}