// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EVCMS.Repositories.DucPV.Models;

public partial class Notification
{
    public int NotificationId { get; set; }

    public int? UserAccountId { get; set; }

    public string Title { get; set; }

    public string Body { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public bool? Status { get; set; }

    public virtual UserAccount UserAccount { get; set; }
}