// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EVCMS.Repositories.DucPV.Models;

public partial class PaymentMethodsDucPv
{
    public int MethodDucPvid { get; set; }

    public string MethodType { get; set; }

    public bool? Status { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual ICollection<TransactionsDucPv> TransactionsDucPvs { get; set; } = new List<TransactionsDucPv>();
}