// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EVCMS.Repositories.DucPV.Models;

public partial class Staff
{
    public int StaffId { get; set; }

    public int? CreatedByAdminId { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public string Email { get; set; }

    public DateTime? StartDate { get; set; }

    public DateTime? EndDate { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public bool? Status { get; set; }

    public virtual ICollection<ChargingStation> ChargingStations { get; set; } = new List<ChargingStation>();

    public virtual Admin CreatedByAdmin { get; set; }

    public virtual ICollection<IssueReport> IssueReports { get; set; } = new List<IssueReport>();
}