// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EVCMS.Repositories.DucPV.Models;

public partial class Subscription
{
    public int SubscriptionId { get; set; }

    public string PlanName { get; set; }

    public string PlanCode { get; set; }

    public string Description { get; set; }

    public decimal? Price { get; set; }

    public int? TypeId { get; set; }

    public decimal? DiscountRate { get; set; }

    public int? CreatedByAdminId { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public bool? Status { get; set; }

    public virtual Admin CreatedByAdmin { get; set; }

    public virtual SubscriptionType Type { get; set; }

    public virtual ICollection<UserSubscription> UserSubscriptions { get; set; } = new List<UserSubscription>();
}