// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EVCMS.Repositories.DucPV.Models;

public partial class UserSubscription
{
    public int UserSubscriptionId { get; set; }

    public int? UserAccountId { get; set; }

    public int? SubscriptionId { get; set; }

    public DateTime? StartDate { get; set; }

    public DateTime? EndDate { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public bool? Status { get; set; }

    public virtual Subscription Subscription { get; set; }

    public virtual UserAccount UserAccount { get; set; }
}