// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EVCMS.Repositories.DucPV.Models;

public partial class ChargingSession
{
    public int SessionId { get; set; }

    public int? PointId { get; set; }

    public decimal? EnergyConsumedKwh { get; set; }

    public int? VehicleId { get; set; }

    public DateTime? StartTime { get; set; }

    public DateTime? EndTime { get; set; }

    public bool? IsFullyCharged { get; set; }

    public bool? Status { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual ChargingPoint Point { get; set; }

    public virtual ICollection<TransactionsDucPv> TransactionsDucPvs { get; set; } = new List<TransactionsDucPv>();

    public virtual Vehicle Vehicle { get; set; }
}