// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EVCMS.Repositories.DucPV.Models;

public partial class TransactionsDucPv
{
    public int TransactionTransactionsDucPvid { get; set; }

    public int? SessionId { get; set; }

    public int? UserAccountId { get; set; }

    public decimal? Amount { get; set; }

    public int? MethodDucPvid { get; set; }

    public string Description { get; set; }

    public DateTime? TransactionDate { get; set; }

    public bool? Status { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual ICollection<Invoice> Invoices { get; set; } = new List<Invoice>();

    public virtual PaymentMethodsDucPv MethodDucPv { get; set; }

    public virtual ChargingSession Session { get; set; }

    public virtual UserAccount UserAccount { get; set; }
}