// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EVCMS.Repositories.DucPV.Models;

public partial class Admin
{
    public int AdminId { get; set; }

    public string ContactEmail { get; set; }

    public string ContactPhone { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public bool? Status { get; set; }

    public virtual ICollection<ChargingStation> ChargingStations { get; set; } = new List<ChargingStation>();

    public virtual ICollection<Staff> Staff { get; set; } = new List<Staff>();

    public virtual ICollection<Subscription> Subscriptions { get; set; } = new List<Subscription>();
}