// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EVCMS.Repositories.DucPV.Models;

public partial class Invoice
{
    public int InvoiceId { get; set; }

    public int? TransactionTransactionsDucPvid { get; set; }

    public string InvoiceData { get; set; }

    public DateTime? IssuedDate { get; set; }

    public bool? Status { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual TransactionsDucPv TransactionTransactionsDucPv { get; set; }
}