// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EVCMS.Repositories.DucPV.Models;

public partial class Reservation
{
    public int ReservationId { get; set; }

    public int? UserAccountId { get; set; }

    public int? PointId { get; set; }

    public DateTime? StartTime { get; set; }

    public DateTime? EndTime { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public bool? Status { get; set; }

    public virtual ChargingPoint Point { get; set; }

    public virtual UserAccount UserAccount { get; set; }
}