// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EVCMS.Repositories.DucPV.Models;

public partial class Vehicle
{
    public int VehicleId { get; set; }

    public int? UserAccountId { get; set; }

    public string LicensePlate { get; set; }

    public string VehicleModel { get; set; }

    public string ConnectorType { get; set; }

    public bool? Status { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual ICollection<ChargingSession> ChargingSessions { get; set; } = new List<ChargingSession>();

    public virtual UserAccount UserAccount { get; set; }
}